#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 nix")
    nix eval -f nix/sol1.nix gt-last-count
    ;;
  "2 " | "2 nix")
    nix eval -f nix/sol2.nix gt-last-count
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
