#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 awk")
    awk -f awk/sol1 < input
    ;;
  "2 " | "2 awk")
    awk -f awk/sol2 < input
    ;;
  "1 perl")
    perl perl/sol1 < input
    ;;
  "2 perl")
    perl perl/sol2 < input
    ;;
  "1 haskell")
    (cd ./haskell; cabal run sol1) < input
    ;;
  "2 haskell")
    (cd ./haskell; cabal run sol2) < input
    ;;
  "1 sh")
    ./sh/sol1 < input
    ;;
  "2 sh")
    ./sh/sol2 < input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
