#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 octave")
    cd octave
    octave ./sol1.m
    ;;
  "2 " | "2 octave")
    cd octave
    octave ./sol2.m
    ;;
  "1 " | "1 rust")
    cd rust/sol1
    cargo run < ../../input
    ;;
  "2 " | "2 rust")
    cd rust/sol2
    cargo run < ../../input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
