#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 octave")
    cd octave
    octave ./sol1.m
    ;;
  "2 " | "2 octave")
    cd octave
    octave ./sol2.m
    ;;
  "1 " | "1 j")
    cd j
    cat ./sol1.ijs | ijconsole
    ;;
  "2 " | "2 j")
    cd j
    cat ./sol2.ijs | ijconsole
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
