#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 python")
    python3 ./python/sol1.py <input
    ;;
  "2 " | "2 python")
    python3 ./python/sol2.py <input
    ;;
  "1 " | "1 scala")
    cd scala
    scala ./sol1.sc
    ;;
  "2 " | "2 scala")
    cd scala
    scala ./sol2.sc
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
