#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 ruby")
    ruby ./ruby/sol1.rb <input
    ;;
  "2 " | "2 ruby")
    ruby ./ruby/sol2.rb <input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
