#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 ruby")
    ruby ./ruby/sol1.rb <input
    ;;
  "2 " | "2 ruby")
    ruby ./ruby/sol2.rb <input
    ;;
  "1 " | "1 perl")
    perl ./perl/sol1.pl <input
    ;;
  "2 " | "2 perl")
    perl ./perl/sol2.pl <input
    ;;
  "1 " | "1 dc")
    dc -f <(tr ',' '\n' <input) dc/sol1.dc
    ;;
  "2 " | "2 dc")
    dc -f <(tr ',' '\n' <input) dc/sol2.dc
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
