#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 nix")
    nix eval -f nix/sol1 gt-last-count
    ;;
  "2 " | "2 nix")
    nix eval -f nix/sol2 gt-last-count
    ;;
  "1 j")
    cd j
    cat sol1.ijs | ijconsole
    ;;
  "2 j")
    cd j
    cat sol2.ijs | ijconsole
    ;;
  "1 jq")
    ./jq/sol1 < input
    ;;
  "2 jq")
    ./jq/sol2 < input
    ;;
  "1 haskell")
    runghc ./haskell/sol1.hs < input
    ;;
  "2 haskell")
    runghc ./haskell/sol2.hs < input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
