#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 nix")
    nix eval -f nix/sol1 gt-last-count
    ;;
  "2 " | "2 nix")
    nix eval -f nix/sol2 gt-last-count
    ;;
  "1 j")
    cd j
    cat sol1.j | ijconsole
    ;;
  "2 j")
    cd j
    cat sol2.j | ijconsole
    ;;
  "1 jq")
    ./jq/sol1 < input
    ;;
  "2 jq")
    ./jq/sol2 < input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
