#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 python")
    python3 ./python/sol1.py <input
    ;;
  "2 " | "2 python")
    python3 ./python/sol2.py <input
    ;;
  "1 " | "1 awk")
    awk -f ./awk/sol1.awk <input
    ;;
  "2 " | "2 awk")
    awk -f ./awk/sol2.awk <input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
