#!/usr/bin/env bash
case "$1 $2" in
  "1 " | "1 awk")
    awk -f sol1.awk < input
    ;;
  "2 " | "2 awk")
    awk -f sol2.awk < input
    ;;
  "1 perl")
    perl sol1.pl < input
    ;;
  "2 perl")
    perl sol2.pl < input
    ;;
  "1 haskell")
    (cd ./hs; cabal run sol1) < input
    ;;
  "2 haskell")
    (cd ./hs; cabal run sol2) < input
    ;;
  *)
    echo "Unrecognized solution '$1 $2'" 1>&2
    exit 1
    ;;
esac
